Write-Host "Deployment completed successfully!" -ForegroundColor Green
Write-Host ""

# Get the outputs from the deployment
$outputs = azd env get-values --output json | ConvertFrom-Json

Write-Host "Creating .env file for event generator..." -ForegroundColor Yellow

# Create the .env file for the event generator
$envContent = @"
# Event Generator Configuration - Generated by azd postprovision
# Uses DefaultAzureCredential for authentication (Azure CLI locally)

EVENT_HUB_NAMESPACE=$($outputs.eventHubNamespaceFqdn)
EVENT_HUB_NAME=$($outputs.eventHubName)

# Generator settings
POLL_INTERVAL=1

# Note: When running locally, authenticate with Azure CLI: az login
"@
      
# Write the .env file
$envPath = "./event-generator/.env"
$envContent | Out-File -FilePath $envPath -Encoding UTF8

Write-Host "✅ Created $envPath" -ForegroundColor Green
Write-Host ""
Write-Host "Event generator is configured with:" -ForegroundColor Cyan
Write-Host "  Event Hub Namespace: $($outputs.eventHubNamespaceFqdn)" -ForegroundColor White
Write-Host "  Event Hub Name: $($outputs.eventHubName)" -ForegroundColor White
Write-Host "  Authentication: DefaultAzureCredential" -ForegroundColor White
Write-Host ""
Write-Host "To run the event generator:" -ForegroundColor Yellow
Write-Host "  cd event-generator" -ForegroundColor White
Write-Host "  pip install -e ." -ForegroundColor White
Write-Host "  python -m vehicle_generator.cli feed --agency 'demo-transit'" -ForegroundColor White
Write-Host ""
Write-Host "Note: For local development, ensure you're logged in with Azure CLI:" -ForegroundColor Yellow
Write-Host "  az login" -ForegroundColor White